### ISSUE TITLE
Research on necessary endpoints for Creating events task

### ISSUE THREAD

**Issue by hoshion** [fictadvisor/fictadvisor-bot#132]
We have such task in our semester's plan:

![image](https://github.com/fictadvisor/fictadvisor-bot/assets/42845566/a030b95f-01a0-4105-91c1-a7eb37d8299b)

What does it mean?

We would like to have an ability for captain and moderator to create events of type "Other" in schedule through bot.

Functionality:
- Ability to create events of type "Other" (you can enter name, date, start time (hours and minutes), end time (hours and minutes), description (optional), url (optional)), command in DM and Group chat
- Ability to show the list of other events (for the next month), command in DM and Group Chat
- Ability to delete events (for the next month), command in DM and Group chat
- Ability to edit events (for the next month), command in DM and Group chat

**The task is to say what endpoints and tables in database should back-end have. It must be fully described with essential requests, responses, fields, queries, data types, etc.**

**Comment by ukrustacean** [comment]
We already have an endpoint for creating "Other" events: `/v2/schedule/events/simple`. So I made a [spreadsheet](https://docs.google.com/spreadsheets/d/1vat0j_YS0XnQ3hhhrB2Cykf72is9NzOC0wZ-1ux9Cs4/edit?usp=sharing) for all other points we need for backend to have. Note that all of them should have `TelegramGuard` so that it is easy to access them from bot.

**Comment by ukrustacean** [comment]
Now that we have got all the details straight, we have this list of needed endpoints:

- [ ] Make `POST /v2/schedule/events`, `GET /v2/schedule/groups/{groupId}/events/` and `PATCH/DELETE /v2/schedule/groups/{groupId}/events/{eventId}` endpoints accessible from Telegram bot, so that they accept `Authorization` header with token.
- [ ] Add `GET /v2/schedule/groups/{groupId}/month` endpoint. All specs for it are stated in a [spreadsheet](https://docs.google.com/spreadsheets/d/1vat0j_YS0XnQ3hhhrB2Cykf72is9NzOC0wZ-1ux9Cs4/edit?usp=sharing).
- [ ] Add query parameter to filter events from `GET /v2/schedule/groups/{groupId}/{week, fortnight, month}`
